### ISSUE TITLE
Layout fixes

### ISSUE THREAD

**Issue by caiogondim** [zofepod/zofe#100]
PDF with some erros i have found http://cl.ly/3T3h2v0r1221

**Comment by caiogondim** [comment]
@bpassos Could you add the errors you have found as well?

**Comment by bpassos** [comment]
Yep. This page needs some love overall. I have a few ideas and will try to conceptualise them today.

Thanks for creating this task @caiogondim

**Comment by bpassos** [comment]
OK, so at a glance, these are changes we can make to make that page a little better...

The changes were:

• Slight smaller header (logo is smaller)
• style changes to the anchor links on the intro paragraphs
• style changes to the times on the episode timeline
• style changes to the headers on the episode timeline
• The soundcloud player is now encapsulated in its own area, to distinguish from the disqus area and give a little bit more information breakdown on the whole page

Its important to emphasise that this should also be reflected on the responsive version of this page, which looks a little messy now.

What do you think?

Cheers!

![screenshot-zofe com br 2015-03-17 17-30-45](https://cloud.githubusercontent.com/assets/1923332/6692297/3639f4e4-cccc-11e4-88cb-4ac0f63f04ae.png)

**Comment by danielfilho** [comment]
I'd add some padding to the timestamp link, like 3-5px, just like the link for the content.

for all the rest: :shipit:

**Comment by caiogondim** [comment]
Just one thing i discussed about with @bpassos 
We should merge the timestamp and the player in one session.
But i already like a lot.

@bpassos monstro!

**Comment by BuKinoshita** [comment]
- [x] Slight smaller header (logo is smaller) - [fix](https://github.com/zofepod/zofe/pull/109)
- [ ] style changes to the anchor links on the intro paragraphs
- [ ] style changes to the times on the episode timeline
- [ ] style changes to the headers on the episode timeline
- [x] The soundcloud player is now encapsulated in its own area, to distinguish from the disqus area and give a little bit more information breakdown on the whole page - [fix](https://github.com/zofepod/zofe/pull/109)
