### ISSUE TITLE
Create a custom intro to the podcast

### ISSUE THREAD

**Issue by kassyn** [zofepod/zofe#105]
We have many programmers musicians, what about creating a special intro for **zofe**?

**Comment by kassyn** [comment]
Below we have two links, two themes that did. Are just a start, are unmixed and finishing
* [Theme 01](https://www.dropbox.com/s/dxlf38g99jng7kx/theme01.mp3?dl=0)
* [Theme 02](https://www.dropbox.com/s/h1t82egpt1h6fao/theme02.mp3?dl=0)

**Comment by danielfilho** [comment]
not gonna happen. sorry :)

but thanks for the intros. they sound really good!
