### ISSUE TITLE
Fix about page

### ISSUE THREAD

**Issue by danielfilho** [zofepod/zofe#110]
About page is a little messy. Need some attention.

http://zofe.com.br/sobre/

**Comment by bpassos** [comment]
I am taking a look at it tonight

**Comment by pedropolisenso** [comment]
@danielfilho I can send a PR with new style css to structure of the page about?

**Comment by bpassos** [comment]
Hey @pedropolisenso, there is a pull request waiting to be approved with the styles for that page. What did you have in mind? Any screenshots?

Thanks a lot!

**Comment by pedropolisenso** [comment]
Humm Ok @bpassos!
