### ISSUE TITLE
Paginação não está funcionando

### ISSUE THREAD

**Issue by cloudson** [zofepod/zofe#130]
O link para [page2](https://zofe.com.br/page2) retorna um 404. Tentei chutar uns outros padroes de url mas acho que o problema deve estar mais profundo no gerador :cry:  .

**Comment by danielfilho** [comment]
Opa, valeu pelo toque @cloudson, mas eu já sabia. Quando atualizei o Jekyll quebrou a paginação. ele tá sem o `/posts` depois do domínio e antes do nome da página:

ex: `https://zofe.com.br/page2` => `https://zofe.com.br/posts/page2`

eu nem fui atrás de arrumar pra continuar trabalhando na versão nova do site. mas valeu pelo toque. vou deixar a issue aberta até fazer o deploy dita versão!


valeuzão (e se quiser arrumar, seria ❤️)

**Comment by cloudson** [comment]
Legal! Agora que tu me mostrou o caminho das pedras, vou tentar fazer isso essa semana. 
De qualquer forma já fica documentado aqui se alguém esbarrar nessa issue. 

Obrigado.

**Comment by danielfilho** [comment]
@cloudson resolvi o problema da paginação no commit 7dc161f, removendo a paginação por completo (e dando um preview de como vai ser o novo ZOFE, que aliás, falamos no novo episódio sobre a refatoração 😉)

Fechando esse aqui, mas quero agradecer por pegar este probleminha 😬
