### ISSUE TITLE
Criar player persistente

### ISSUE THREAD

**Issue by danielfilho** [zofepod/zofe#67]
Bolar uma maneira de fazer o player da SoundCloud persistir no rodapé da página, e que a navegação toda seja feita com comportamento de SPA para o podcast.

Assim, a pessoa pode navegar no site enquanto ouve o podcast. Sem interrupções.

@bpassos, cria um layout dessa opção? :heart: 

@almirfilho, @caiogondim, @rafaelrinaldi: 
- [SennaJS](http://sennajs.com/)? 
- Passar o ZOFE pra Ember?
- Buscar uma lib que seja 0 fricção pra essa feature apenas?

No caso do Senna, acho MUITA coisa pra resolver só uma coisa. Talvez possamos abstrair a parte de navegação da lib pra usar só ela. Enfim. Vamos discutir :smile:

**Comment by cirocosta** [comment]
:+1: :+1:
Pro SPA eu voto para o uso do Senna dada a facilidade, ser bem pouco intrusivo - precisando de bem pouco aprendizado pelo que ví (nunca usei, na real) -, além de ser Br e super bem feito

**Comment by randsonjs** [comment]
Eu curto bastante o player persistente do próprio soundcloud! Acho ele bem simples e fica ao lado direito da tela. O que acha dessa opção?

Pro SPA também voto no Senna! :smile:

**Comment by bpassos** [comment]
@danielfilho I am on it! :*

**Comment by lucasmazza** [comment]
Algo como o [jquery-pjax](https://github.com/defunkt/jquery-pjax) pode ser mais fácil de adicionar ao projeto sem reescrever o ZOFE como um SPA - desde que o player fique em um elemento fora do conteúdo, com alguma coisa assim:

```html
<body>
  <div data-pjax-container data-title='Title para a troca de página via pjax'>
   <!-- Conteúdo alterado a cada click -->
  </div> 
  <div data-player>
     <!-- Conteúdo fixo -->
  </div>
</body>
```

```js
$(document).pjax('a[data-pjax]', '[data-pjax-container]', { fragment: '[data-pjax-container]' });
```

Existe um trabalho chato de sair clicando em todos os links dos posts existentes e ver se alguma coisa quebrou ou se algum JS deixou de funcionar (depois que uma página nova é carregada via pjax) mas acho que uma solução mais prática a Senna/Ember/whatever.

**Comment by danielfilho** [comment]
sensacional @lucasmazza. 

é exatamente minha preocupação: usar uma lib parruda pra matar um problema pontual. já conhecia o pjax, vou com certeza fazer uma branch e testar esse cara no nosso #66 :)

**Comment by danielfilho** [comment]
done. mas precisa de melhorias.
