### ISSUE TITLE
Feed do podcast não é lido bem pelos agregadores, exceto iTunes

### ISSUE THREAD

**Issue by niltoncms** [zofepod/zofe#68]
Acompanho o podcast através de feed RSS pelo smartphone, e pude notar que o feed dos podcasts não é bem lido por alguns agregadores de podcast incluindo o que uso atualmente, o AntennaPod (Android); exceto pelo iTunes (¬¬). Li o [XML](https://github.com/zofepod/zofe/blob/master/feed/podcast.xml) que concentra esse feed específico e vi que não é muito bem otimizado para outros softwares/protocolos que não seja o iTunes/ITCP. Tô afim de melhorar isso. Bora? :D

**Comment by danielfilho** [comment]
bora @niltoncms :)

**Comment by danielfilho** [comment]
@philss o @rafaelrinaldi deu spoiler que vc também tá com problema. se quiser ajudar nessa task (mas sem deixar que pare de funcionar no itunes), é nóis ;)

**Comment by philss** [comment]
@danielfilho sim cara, o episódio 19 não está disponível pra mim na app que uso. Estranho que o episódio 20 está disponível.
Uso app [PocketCasts](http://www.shiftyjelly.com/pocketcasts) no Android. 
 
@danielfilho @niltoncms posso ajudar nessa issue! Vou ver o formato que essa app usa, e ver se tem algum guideline pra ela (se bem que ela deve usar algum padrão).

**Comment by niltoncms** [comment]
@danielfilho @philss Massa! Philip, faremos isso! 
Já tive testando, mesmo que estaticamente, e vi uma tag aqui que funcionou no app que eu citei. Vamos garimpar na internet e tornar mais acessível para o maior número de clientes possíveis!

Com certeza deve ter uma guideline pra isso, e caso não tenha, é uma ótima chance pra gente montar e uma colocar aqui no github!

**Comment by philss** [comment]
@niltoncms Encontrei um guideline interessante, mas está incompleta: https://github.com/gpodder/podcast-feed-best-practice/blob/master/podcast-feed-best-practice.md

Também testei o feed do Zofe no [W3C validator](http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fzofe.com.br%2Ffeed%2Fpodcast.xml).

O único erro relevante é o formato do atributo `length` na tag `enclosure` (`/rss/channel/item/enclosure`). Esse atributo deve ser um número inteiro, e representa o [tamanho do arquivo em bytes](http://www.rssboard.org/rss-specification#ltenclosuregtSubelementOfLtitemgt).

Dá para saber o tamanho em bytes usando o `cURL`:

```
$ curl -I -L http://feeds.soundcloud.com/stream/192038747-zofepod-zofe-20-dois-ponto-zero-finalmente
```

Ele retorna o header `Content-Length`, que é o que queremos. Vamos ter que fazer isso para todos os episódios existentes. Nada que um script não resolva.

**Comment by caiogondim** [comment]
:+1: Boa, @philss 
Amanhã vou dar uma olhada nessa issue.

**Comment by danielfilho** [comment]
boa @philss e @niltoncms! demais mesmo!

leva essa @caiogondim, nesse final de semana ficarei longe do computador :/

de qqr forma, hoje tirei pra tentar configurar um ambiente de stage pra gente testar antes de ir pra produção :)

**Comment by caiogondim** [comment]
Ok.
Vou matar essa issue com o @philss

**Comment by philss** [comment]
@danielfilho @caiogondim Boa! Abri esse [PR](https://github.com/zofepod/zofe/pull/72) pra consertar o `length`. Podemos testar quando o @danielfilho puder subir em staging.

@caiogondim Como diz o @rafaelrinaldi: vamo crescer junto! O @niltoncms também está dentro. Ele está testando o XML em um servidor, com a app que ele usa.

Amanhã talvez eu não consiga, mas domingo estarei por aqui.

**Comment by niltoncms** [comment]
@philss Testei a modificação que você fez e ficou sensacional, é isso mesmo! :)))
Vou fazer como tu sugeriu: app lá no Heroku pra todo mundo poder testar live com o Jekyll rodando (por enquanto tô fazendo estaticamente direto no XML)

**Comment by caiogondim** [comment]
Eu acabei dar um `build` da sua PR e joguei em nessa URL pra que a gente possa testar: http://tmp.caiogondim.com

Vou tentar replicar o erro aqui em um Android e então ver se o PR resolveu.
Vocês podem testar também e dar esse feedback?

**Comment by niltoncms** [comment]
Ótimo, valeu, @caiogondim !

Sim, comigo funcionou corretamente.

**Comment by niltoncms** [comment]
@danielfilho @caiogondim Pessoas, abri um [PR](https://github.com/zofepod/zofe/issues/74) pra adicionar mais duas tags. Se a gente puder testar com o subdomínio do Caio seria bem interessante :)))

**Comment by caiogondim** [comment]
Vou subir para o meu dominio de teste amanhã.

**Comment by caiogondim** [comment]
Desculpa a demora.
Ainda há a necessidade de testar isto?

**Comment by danielfilho** [comment]
nope. já testei e tá em prod 😁

**Comment by cassiocardoso** [comment]
Pessoal, estou usando o Overcast para ouvir meus podcasts e acabei de ter o mesmo problema.

**Comment by danielfilho** [comment]
@cassiocardoso que doidera. eu uso o overcast e aqui tá maravilhoso de lindo.

![screen shot 2015-09-14 at 18 43 57](https://cloud.githubusercontent.com/assets/24597/9862659/a1944c6c-5b10-11e5-9081-1bdc482db090.png)

**Comment by niltoncms** [comment]
@cassiocardoso manda um print aí. Usando no meu Android achei a interface ~nativamente~ bagunçada, e talvez o do @danielfilho seja iPhone e esteja tudo diretinho.

**Comment by cassiocardoso** [comment]
O meu é um iPhone também @niltoncms. Testei agora e consegui achar certinho. Valeu galera.
