### ISSUE TITLE
Menu is broken in small resolutions

### ISSUE THREAD

**Issue by raphaelfabeni** [zofepod/zofe#69]
![captura de tela 2015-02-20 as 15 18 20](https://cloud.githubusercontent.com/assets/1345662/6305633/e56b6d20-b913-11e4-85ef-d54fdce46eee.png)

**Comment by danielfilho** [comment]
o cara tira folga mas continua trampando pro zofe. <3 fabeni.
hahaha

**Comment by rafaelrinaldi** [comment]
Boa @raphaelfabeni!

**Comment by raphaelfabeni** [comment]
Folga é pra você fazer as coisas que você gosta! :tea: :metal:

**Comment by danielfilho** [comment]
boa! hahaha
