### ISSUE TITLE
Facebook meta tags

### ISSUE THREAD

**Issue by mauriciosoares** [zofepod/zofe#76]
It would be nice to set some facebook meta tags like og:image, I just saw a share of your site and it appeared a beautiful photo of @rafaelrinaldi :D

![screen shot 2015-02-24 at 13 21 53](https://cloud.githubusercontent.com/assets/2321259/6353459/1f4599dc-bc28-11e4-91ce-96c6107e4119.png)

**Comment by danielfilho** [comment]
🚢
