### ISSUE TITLE
Quebra de layout

### ISSUE THREAD

**Issue by ftonato** [zofepod/zofe#77]
Na página inicial do [ZOFE](http://zofe.com.br/), a última postagem está quebrando o layout de dispositivos móveis largura <= 400px.

![erro-zofe](https://cloud.githubusercontent.com/assets/5417662/6397076/06e25426-bdc1-11e4-9ab3-7ee0ff85351c.png)

`#main-content > div.latest-post.u-full-width > article > header > h2 > a.latest-post-title`
Está com `font-size: 62px` e aí está o problema :)

Em uma conversa com o @philss surgiu duas sugestões:
> Eu imagino que a solução seja usar `em` em vez de `px` ali, ou quebrar o texto que der overflow

Abraços

**Comment by danielfilho** [comment]
valeu o reporte galera, tem duas coisas que tou trabalhando:

- minificar e ter um deploy melhor dos assets
- corrigir exatamente esse bug em mobile :D

mas quem quiser ajudar, go for it!

**Comment by niltoncms** [comment]
Massa @ftonato, bora lá :DD
Cara, depois de uma inspecionada aqui, vi que esse `a.latest-post-title` que tá estilizado com `font-size: 62px` tá sobrescrevendo o font-size do h2 pai, que está correto! Dá uma comentada nesse font-size que o estilo correto vai ser aplicado, no caso o font-size do h2 `font-size: 3.6rem`, e diz aí o que tu acha :))))

**Comment by ftonato** [comment]
Certo, @niltoncms acabei de ver, mas a pergunta agora é:
O `a.latest-post-title` que é o título de uma postagem em *destaque* vai ficar menor que os outros títulos?

`a.latest-post-title` com `font-size: 3.6rem`
`a.episode-title` com `font-size: 1.2em`

**Comment by niltoncms** [comment]
Tem toda a razão sobre a questão do tamanho!
Caso substituir `62px` por `1.2em` nele mesmo ficaria de tamanho e estilo iguais aos outros `<h2>`.
Por mim, os dois com o mesmo tamanho não fariam diferença visual pois há outros elementos já destacando.
Minha dica: tirar o `62px` por `1.2em` no `a.latest-post-title` e pronto!

Mas essa aqui vai com o @danielfilho :))

**Comment by bpassos** [comment]
Nesse screenshot o header ta zoado, mandei um PR com o fix

**Comment by danielfilho** [comment]
valeu pelo fix, @bpassos :)
