### ISSUE TITLE
Improve legibility of post list on responsive layout.

### ISSUE THREAD

**Issue by bpassos** [zofepod/zofe#86]
Currently the post title and post excerpt are quite large on the responsive version of the site:
![screen shot 2015-03-04 at 18 24 32](https://cloud.githubusercontent.com/assets/1923332/6489098/07c986c2-c29c-11e4-81d8-0780865af940.png)

What do you guys think about this as a solution?
![screen shot 2015-03-04 at 18 23 53](https://cloud.githubusercontent.com/assets/1923332/6489105/16cf0e76-c29c-11e4-8b4f-68829a0cc53a.png)

**Comment by caiogondim** [comment]
Achei bem melhor
