### ISSUE TITLE
Fix proportions and margins around the prev/ next button

### ISSUE THREAD

**Issue by bpassos** [zofepod/zofe#89]
![screen shot 2015-03-05 at 10 01 56](https://cloud.githubusercontent.com/assets/1923332/6501931/cfdcd970-c31e-11e4-9227-85317ae44542.png)

![screen shot 2015-03-05 at 10 02 08](https://cloud.githubusercontent.com/assets/1923332/6501933/d2387242-c31e-11e4-8172-664f7452f686.png)

**Comment by bpassos** [comment]
For some reason the transform: rotate(90deg) property is not being triggered on chrome

**Comment by bpassos** [comment]
working on a fix...

**Comment by danielfilho** [comment]
nice @bpassos 
just make sure to test before pushing the code :cry:

**Comment by bpassos** [comment]
Sure thing... I only spotted the error when looking on the iphone. On the desktop browser it worked fine. But yes, testing++
