### ISSUE TITLE
Trampos following the same layout as the rest of the site

### ISSUE THREAD

**Issue by bpassos** [zofepod/zofe#94]
It could be a submodule inside /Trampos

![zofe 1_trampos](https://cloud.githubusercontent.com/assets/1923332/6530253/7c9427c0-c42f-11e4-8d4a-ebc6075777d0.jpg)

**Comment by joridos** [comment]
Someone working on it?

**Comment by danielfilho** [comment]
yup, @bpassos is. but any support is welcome :)

**Comment by joridos** [comment]
Nice, @bpassos started to do something?

**Comment by bpassos** [comment]
@joridos I did, but haven't gone very far with it yet, quite busy at the moment. Feel free to grab it. Cheers!

**Comment by joridos** [comment]
Ok  :smiley:

**Comment by bpassos** [comment]
@joridos what is the progress of this task? cheers!

**Comment by joridos** [comment]
I not work on it yet @bpassos, sorry. cheers!

**Comment by bpassos** [comment]
@joridos no worries!

**Comment by BuKinoshita** [comment]
I just did some work on this: https://github.com/zofepod/trampos/pull/20

Still in progress though, need to work on the `inner pages` and `pagination`.

Also moved the entire project to Sass w/ Grunt (https://github.com/zofepod/zofe/pull/66)

**Comment by danielfilho** [comment]
oh, we're thinking about deprecate zofe trampos, @BuKinoshita.
although your job is awesome! just saw it :)

thank you very much for contributing :smiley:

**Comment by BuKinoshita** [comment]
:wink:

**Comment by danielfilho** [comment]
trampos is dead. long live trampos.
