### ISSUE TITLE
Make show-notes links open in new window

### ISSUE THREAD

**Issue by danielfilho** [zofepod/zofe#98]
Add a `target="_blank"` into show-notes links.

**Comment by filipelinhares** [comment]
I've saw how to do that but with md the has no way i guess.
i searched and found [it](http://stackoverflow.com/questions/4425198/markdown-target-blank). I don't have much job to do this week if you want to change all links manually i can do that hahaha, or some js alternative, anyway if you want some help i'm here.

**Comment by danielfilho** [comment]
all we need to do is a script that checks the show-notes links and add an attr `target=_blank` :)

I've set this as a to-do list.

**Comment by danielGalvao** [comment]
this issue is still needed?

**Comment by bpassos** [comment]
Yes @danielGalvao AFAIK

**Comment by filipelinhares** [comment]
@bpassos this was solved [here](https://github.com/zofepod/zofe/blob/master/assets/js/scripts.js#L19-L24) I guess.

**Comment by bpassos** [comment]
Perfect then @filipelinhares && @danielgalvao lets close this issue. Cheers!
